label:
		gcc -c circularLinkedlist.c
		gcc -c stack.c
		gcc -c queue.c
		gcc -c stackLinkedList.c
		gcc -c queueLinkedList.c
		gcc -c circularQueueLinkedList.c
		gcc circularLinkedlist.o -o circular
		gcc stack.o -o stack
		gcc queue.o -o queue
		gcc stackLinkedList.o -o stackLinkedList
		gcc queueLinkedList.o -o queueLinkedList
		gcc circularQueueLinkedList.o -o circularQueueLinkedList
		
clean:
		rm *.o circular stack queue stackLinkedList queueLinkedList circularQueueLinkedList *.out