label:
	gcc -c Matrix_multiplication.c
	gcc -c StringReverseNormal.c
	gcc -c ReverseAWord.c
	gcc -c ReverseAWordPosition.c
	gcc -c MyStringCompare.c
	gcc -c wordDeleteFromString.c
	gcc -c stringConcatenationAndStringLength.c
	gcc -c MyATOI.c
	gcc -c My_strStr.c
	gcc -c RunLength.c
	gcc -c RunLengthOpt.c
	
	gcc Matrix_multiplication.o -o Matrix
	gcc StringReverseNormal.o -o StringReverse
	gcc ReverseAWord.o -o RevAWord
	gcc ReverseAWordPosition.o -o PositionReverse
	gcc MyStringCompare.o -o MyStringCompare
	gcc wordDeleteFromString.o -o WordDeleteFromString
	gcc stringConcatenationAndStringLength.o -o strCatLen
	gcc MyATOI.o -o MyATOI
	gcc My_strStr.o -o MYStrstr
	gcc RunLength.o -o RunLen
	gcc RunLengthOpt.o -o RunOptLen
		
cleanall:
		rm -rf *.o *.out Matrix StringNor RevAWord StringReverse PositionReverse MyStringCompare WordDeleteFromString strCatLen MyATOI MYStrstr RunLen RunOptLen 
		
clean: 
		rm -rf *.o *.out