label:
	gcc -c Matrix_multiplication.c
	gcc -c StringReverseNormal.c
	gcc -c ReverseAWord.c
	gcc -c ReverseAWordPosition.c
	gcc -c MyStringCompare.c
	gcc -c wordDeleteFromString.c
	gcc -c stringConcatenationAndStringLength.c
	
	gcc Matrix_multiplication.o -o Matrix
	gcc StringReverseNormal.o -o StringReverse
	gcc ReverseAWord.o -o RevAWord
	gcc ReverseAWordPosition.o -o PositionReverse
	gcc MyStringCompare.o -o MyStringCompare
	gcc wordDeleteFromString.o -o WordDeleteFromString
	gcc stringConcatenationAndStringLength.o -o strCatLen
		
cleanall:
		rm -rf *.o Matrix StringNor RevAWord StringReverse PositionReverse MyStringCompare WordDeleteFromString strCatLen 
		
clean: 
		rm -rf *.o