label:
	gcc check_armstrongNo.c -o check_armstrongNo
	gcc check_oddEven.c -o check_oddEven
	gcc check_primeNo.c -o check_primeNo	
	gcc factorial.c -o factorial
	gcc palindrome_number.c -o palindrome_number
	gcc perfect_square.c -o perfect_square
	gcc print_withOut_semi.c -o print_withOut_semi
	gcc swap_2nos_Nt3var.c -o swap_2nos_Nt3var
	gcc swap_bits.c -o swap_bits
	gcc swap_word_nibbles.c -o swap_word_nibbles
	gcc leapYear.c -o leapYear
	gcc genericLinkList.c -o genericLinkList
		
clean:
	rm check_armstrongNo check_oddEven check_primeNo factorial palindrome_number perfect_square print_withOut_semi swap_2nos_Nt3var swap_bits swap_word_nibbles leapYear genericLinkList