label:
		gcc -c bubbleSort.c
		gcc -c selectionSort.c
		gcc -c insertionSort.c
		gcc -c mergeSort.c
		gcc -c quickSort.c
		gcc bubbleSort.o -o bubbleSort
		gcc selectionSort.o -o selectionSort
		gcc insertionSort.o -o insertionSort
		gcc mergeSort.o -o mergeSort
		gcc quickSort.o -o quickSort
		
clean:
	rm *.o *.out bubbleSort selectionSort insertionSort mergeSort quickSort