label:
		gcc -c bubbleSort.c
		gcc -c selectionSort.c
		gcc -c insertionSort.c
		gcc bubbleSort.o -o bubbleSort
		gcc selectionSort.o -o selectionSort
		gcc insertionSort.o -o insertionSort
		
clean:
	rm *.o *.out bubbleSort selectionSort insertionSort